export const MOCK_CATEGORY_DATA = [
  { month: "Jan", desktop: 186, mobile: 80 },
  { month: "Feb", desktop: 305, mobile: 200 },
  { month: "Mar", desktop: 237, mobile: 120 },
  { month: "Apr", desktop: 73, mobile: 190 },
  { month: "May", desktop: 209, mobile: 130 },
  { month: "Jun", desktop: 214, mobile: 140 },
  { month: "Jul", desktop: 102, mobile: 43 },
  { month: "Aug", desktop: 90, mobile: 92 },
  { month: "Sep", desktop: 240, mobile: 170 },
  { month: "Oct", desktop: 141, mobile: 180 },
  { month: "Nov", desktop: 142, mobile: 190 },
  { month: "Dec", desktop: 143, mobile: 200 },
]

export const MOCK_TIME_DATA = [
  {
    timestamp: new Date("2025-01-01").getTime(),
    value: 200,
  },
  {
    timestamp: new Date("2025-01-02").getTime(),
    value: 10239,
  },
  {
    timestamp: new Date("2025-01-03").getTime(),
    value: 12521,
  },
  {
    timestamp: new Date("2025-01-04").getTime(),
    value: 9127,
  },
  {
    timestamp: new Date("2025-01-05").getTime(),
    value: 18921,
  },
  {
    timestamp: new Date("2025-01-06").getTime(),
    value: 17201,
  },
  {
    timestamp: new Date("2025-01-07").getTime(),
    value: 13081,
  },
  {
    timestamp: new Date("2025-01-08").getTime(),
    value: 19020,
  },
  {
    timestamp: new Date("2025-01-09").getTime(),
    value: 10914,
  },
  {
    timestamp: new Date("2025-01-10").getTime(),
    value: 7320,
  },
]

export const MOCK_CURVE_DATA = [
  {
    x: 0,
    y: 0,
    current: false,
    currentSecondary: false,
  },
  {
    x: 10,
    y: 0,
    current: false,
    currentSecondary: false,
  },
  {
    x: 20,
    y: 0,
    current: false,
    currentSecondary: false,
  },
  {
    x: 30,
    y: 0,
    current: true,
    currentSecondary: false,
  },
  {
    x: 40,
    y: 0.02,
    current: false,
    currentSecondary: true,
  },
  {
    x: 50,
    y: 0.04,
    current: false,
    currentSecondary: false,
  },
  {
    x: 60,
    y: 0.1,
    current: false,
    currentSecondary: false,
  },
  {
    x: 70,
    y: 0.19,
    current: false,
    currentSecondary: false,
  },
  {
    x: 80,
    y: 0.32,
    current: false,
    currentSecondary: false,
  },
  {
    x: 90,
    y: 0.52,
    current: false,
    currentSecondary: false,
  },
  {
    x: 100,
    y: 0.79,
    current: false,
    currentSecondary: false,
  },
  {
    x: 110,
    y: 1.15,
    current: false,
    currentSecondary: false,
  },
  {
    x: 120,
    y: 1.63,
    current: false,
    currentSecondary: false,
  },
  {
    x: 130,
    y: 2.23,
    current: false,
    currentSecondary: false,
  },
  {
    x: 140,
    y: 2.98,
    current: false,
    currentSecondary: false,
  },
  {
    x: 150,
    y: 3.89,
    current: false,
    currentSecondary: false,
  },
  {
    x: 160,
    y: 4.98,
    current: false,
    currentSecondary: false,
  },
  {
    x: 170,
    y: 6.26,
    current: false,
    currentSecondary: false,
  },
  {
    x: 180,
    y: 7.74,
    current: false,
    currentSecondary: false,
  },
  {
    x: 190,
    y: 9.44,
    current: false,
    currentSecondary: false,
  },
  {
    x: 200,
    y: 11.34,
    current: false,
    currentSecondary: false,
  },
  {
    x: 210,
    y: 13.46,
    current: false,
    currentSecondary: false,
  },
  {
    x: 220,
    y: 15.78,
    current: false,
    currentSecondary: false,
  },
  {
    x: 230,
    y: 18.29,
    current: false,
    currentSecondary: false,
  },
  {
    x: 240,
    y: 20.97,
    current: false,
    currentSecondary: false,
  },
  {
    x: 250,
    y: 23.8,
    current: false,
    currentSecondary: false,
  },
  {
    x: 260,
    y: 26.77,
    current: false,
    currentSecondary: false,
  },
  {
    x: 270,
    y: 29.83,
    current: false,
    currentSecondary: false,
  },
  {
    x: 280,
    y: 32.96,
    current: false,
    currentSecondary: false,
  },
  {
    x: 290,
    y: 36.13,
    current: false,
    currentSecondary: false,
  },
  {
    x: 300,
    y: 39.32,
    current: false,
    currentSecondary: false,
  },
  {
    x: 310,
    y: 42.48,
    current: false,
    currentSecondary: false,
  },
  {
    x: 320,
    y: 45.61,
    current: false,
    currentSecondary: false,
  },
  {
    x: 330,
    y: 48.68,
    current: false,
    currentSecondary: false,
  },
  {
    x: 340,
    y: 51.66,
    current: false,
    currentSecondary: false,
  },
  {
    x: 350,
    y: 54.55,
    current: false,
    currentSecondary: false,
  },
  {
    x: 360,
    y: 57.33,
    current: false,
    currentSecondary: false,
  },
  {
    x: 370,
    y: 59.98,
    current: false,
    currentSecondary: false,
  },
  {
    x: 380,
    y: 62.52,
    current: false,
    currentSecondary: false,
  },
  {
    x: 390,
    y: 64.92,
    current: false,
    currentSecondary: false,
  },
  {
    x: 400,
    y: 67.19,
    current: false,
    currentSecondary: false,
  },
  {
    x: 410,
    y: 69.33,
    current: false,
    currentSecondary: false,
  },
  {
    x: 420,
    y: 71.34,
    current: false,
    currentSecondary: false,
  },
  {
    x: 430,
    y: 73.22,
    current: false,
    currentSecondary: false,
  },
  {
    x: 440,
    y: 74.99,
    current: false,
    currentSecondary: false,
  },
  {
    x: 450,
    y: 76.63,
    current: false,
    currentSecondary: false,
  },
  {
    x: 460,
    y: 78.17,
    current: false,
    currentSecondary: false,
  },
  {
    x: 470,
    y: 79.6,
    current: false,
    currentSecondary: false,
  },
  {
    x: 480,
    y: 80.94,
    current: false,
    currentSecondary: false,
  },
  {
    x: 490,
    y: 82.18,
    current: false,
    currentSecondary: false,
  },
  {
    x: 500,
    y: 83.33,
    current: false,
    currentSecondary: false,
  },
  {
    x: 510,
    y: 84.4,
    current: false,
    currentSecondary: false,
  },
  {
    x: 520,
    y: 85.39,
    current: false,
    currentSecondary: false,
  },
  {
    x: 530,
    y: 86.32,
    current: false,
    currentSecondary: false,
  },
  {
    x: 540,
    y: 87.18,
    current: false,
    currentSecondary: false,
  },
  {
    x: 550,
    y: 87.98,
    current: false,
    currentSecondary: false,
  },
  {
    x: 560,
    y: 88.72,
    current: false,
    currentSecondary: false,
  },
  {
    x: 570,
    y: 89.41,
    current: false,
    currentSecondary: false,
  },
  {
    x: 580,
    y: 90.05,
    current: false,
    currentSecondary: false,
  },
  {
    x: 590,
    y: 90.64,
    current: false,
    currentSecondary: false,
  },
  {
    x: 600,
    y: 91.2,
    current: false,
    currentSecondary: false,
  },
  {
    x: 610,
    y: 91.71,
    current: false,
    currentSecondary: false,
  },
  {
    x: 620,
    y: 92.2,
    current: false,
    currentSecondary: false,
  },
  {
    x: 630,
    y: 92.64,
    current: false,
    currentSecondary: false,
  },
  {
    x: 640,
    y: 93.06,
    current: false,
    currentSecondary: false,
  },
  {
    x: 650,
    y: 93.45,
    current: false,
    currentSecondary: false,
  },
  {
    x: 660,
    y: 93.81,
    current: false,
    currentSecondary: false,
  },
  {
    x: 670,
    y: 94.15,
    current: false,
    currentSecondary: false,
  },
  {
    x: 680,
    y: 94.47,
    current: false,
    currentSecondary: false,
  },
  {
    x: 690,
    y: 94.77,
    current: false,
    currentSecondary: false,
  },
  {
    x: 700,
    y: 95.05,
    current: false,
    currentSecondary: false,
  },
  {
    x: 710,
    y: 95.31,
    current: false,
    currentSecondary: false,
  },
  {
    x: 720,
    y: 95.55,
    current: false,
    currentSecondary: false,
  },
  {
    x: 730,
    y: 95.78,
    current: false,
    currentSecondary: false,
  },
  {
    x: 740,
    y: 95.99,
    current: false,
    currentSecondary: false,
  },
  {
    x: 750,
    y: 96.19,
    current: false,
    currentSecondary: false,
  },
  {
    x: 760,
    y: 96.38,
    current: false,
    currentSecondary: false,
  },
  {
    x: 770,
    y: 96.56,
    current: false,
    currentSecondary: false,
  },
  {
    x: 780,
    y: 96.73,
    current: false,
    currentSecondary: false,
  },
  {
    x: 790,
    y: 96.89,
    current: false,
    currentSecondary: false,
  },
]
