/**
 * Vendors snakewatch's emoji table into the repo so avatar parity is
 * reviewable in a diff instead of fetched at runtime.
 *
 * Run: yarn workspace @galacticcouncil/ui sync:emoji
 */
import { mkdir, rm, writeFile } from "node:fs/promises"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

import { AccountId } from "polkadot-api"
import prettier from "prettier"

const SOURCE =
  "https://raw.githubusercontent.com/galacticcouncil/snakewatch/refs/heads/main/src/utils/emojify.js"

const OUT_DIR = join(
  dirname(fileURLToPath(import.meta.url)),
  "../src/components/AccountAvatar/emoji",
)
const IMAGE_DIR = join(OUT_DIR, "images")

const DISCORD_EMOJI = /^<(a?):([^:>]+):(\d+)>$/

// ponytail: the source is a hand-maintained JS file with two object/array
// literals in it — a regex plus JSON.parse beats pulling in a JS parser.
const parseLiteral = (source, pattern) => {
  const match = source.match(pattern)
  if (!match) throw new Error(`could not find ${pattern} in ${SOURCE}`)
  return JSON.parse(
    match[1].replace(/'/g, '"').replace(/,(\s*[\]}])/g, "$1"), // drop trailing commas
  )
}

/**
 * Five glyphs upstream lack emoji presentation and render as monochrome text
 * on Windows. Detected by Unicode property, not by index.
 */
const withEmojiPresentation = (glyph) =>
  [...glyph].length === 1 &&
  /\p{Emoji}/u.test(glyph) &&
  !/\p{Emoji_Presentation}/u.test(glyph)
    ? `${glyph}️`
    : glyph

const main = async () => {
  const response = await fetch(SOURCE)
  if (!response.ok) throw new Error(`${SOURCE} -> ${response.status}`)
  const source = await response.text()

  const rawEmojis = parseLiteral(source, /const emojis = (\[[\s\S]*?\]);/)
  const rawDegens = parseLiteral(source, /const degens = (\{[\s\S]*?\});/)

  const emojis = rawEmojis.map(withEmojiPresentation)
  const patched = emojis.filter((glyph, i) => glyph !== rawEmojis[i]).length
  if (patched !== 5) {
    throw new Error(`expected 5 glyphs to need U+FE0F, patched ${patched}`)
  }

  await rm(IMAGE_DIR, { recursive: true, force: true })
  await mkdir(IMAGE_DIR, { recursive: true })

  const accountId = AccountId()
  const degens = {}
  const images = new Map() // discord id -> import identifier

  for (const [address, value] of Object.entries(rawDegens)) {
    const publicKey = `0x${Buffer.from(accountId.enc(address)).toString("hex")}`
    const custom = value.match(DISCORD_EMOJI)

    if (!custom) {
      degens[publicKey] = { emoji: withEmojiPresentation(value) }
      continue
    }

    const [, animated, name, id] = custom
    if (animated) throw new Error(`animated emoji not supported: ${value}`)

    if (!images.has(id)) {
      const url = `https://cdn.discordapp.com/emojis/${id}.webp?size=64`
      const image = await fetch(url)
      if (!image.ok) throw new Error(`${url} -> ${image.status}`)
      await writeFile(
        join(IMAGE_DIR, `${id}.webp`),
        Buffer.from(await image.arrayBuffer()),
      )
      images.set(id, `${name.replace(/\W/g, "")}_${id}`)
    }

    degens[publicKey] = { image: images.get(id) }
  }

  // sorted by module path — simple-import-sort lints the generated file too
  const imports = [...images]
    .sort(([a], [b]) => a.localeCompare(b, undefined, { numeric: true }))
    .map(([id, ident]) => `import ${ident} from "./images/${id}.webp"`)
    .join("\n")

  const entries = Object.entries(degens)
    .map(([key, value]) =>
      "image" in value
        ? `  "${key}": { image: ${value.image} },`
        : `  "${key}": { emoji: ${JSON.stringify(value.emoji)} },`,
    )
    .join("\n")

  const file = `// Generated by \`yarn workspace @galacticcouncil/ui sync:emoji\` on ${new Date().toISOString().slice(0, 10)}.
// Source: ${SOURCE}
// Do not edit by hand — re-run the script instead.

${imports}

export const EMOJIS: readonly string[] = ${JSON.stringify(emojis, null, 2)}

export const DEGENS: Readonly<
  Record<string, { emoji: string } | { image: string }>
> = {
${entries}
}
`

  await writeFile(
    join(OUT_DIR, "snakewatch.ts"),
    await prettier.format(file, { filepath: "snakewatch.ts", semi: false }),
  )

  console.log(
    `${emojis.length} emojis, ${Object.keys(degens).length} degens (${images.size} discord images)`,
  )
}

main()
