// Generated by `yarn workspace @galacticcouncil/ui sync:emoji` on 2026-09-04.
// Source: https://raw.githubusercontent.com/galacticcouncil/snakewatch/refs/heads/main/src/utils/emojify.js
// Do not edit by hand — re-run the script instead.

import buffdoge_989553819539103764 from "./images/989553819539103764.webp"
import thuglife_989554541357834261 from "./images/989554541357834261.webp"
import heimdall_1005035405864869939 from "./images/1005035405864869939.webp"
import bulbasaur_1064486523715719208 from "./images/1064486523715719208.webp"
import polkadot_1064520790978080818 from "./images/1064520790978080818.webp"
import kraken_1068218238074376193 from "./images/1068218238074376193.webp"
import sir_1069817913088946276 from "./images/1069817913088946276.webp"
import Parakeet_1074721851550466219 from "./images/1074721851550466219.webp"
import Charizard_1074723144209809519 from "./images/1074723144209809519.webp"
import Venusaur_1074723145518432268 from "./images/1074723145518432268.webp"
import Dragonite_1074723182944198666 from "./images/1074723182944198666.webp"
import moonbeam_1390048945023094966 from "./images/1390048945023094966.webp"
import HOLLAR_1419786409664970834 from "./images/1419786409664970834.webp"
import HDX_1419786558357377185 from "./images/1419786558357377185.webp"

export const EMOJIS: readonly string[] = [
  "🐵",
  "🐒",
  "🦍",
  "🦧",
  "🐶",
  "🐕",
  "🦮",
  "🐕‍🦺",
  "🐩",
  "🐺",
  "🦊",
  "🦝",
  "🐱",
  "🐈",
  "🐈‍⬛",
  "🦁",
  "🐯",
  "🐅",
  "🐆",
  "🐴",
  "🐎",
  "🦄",
  "🦓",
  "🦌",
  "🐮",
  "🐂",
  "🐃",
  "🐄",
  "🐷",
  "🐖",
  "🐗",
  "🐽",
  "🐏",
  "🐑",
  "🐐",
  "🐪",
  "🐫",
  "🦙",
  "🦒",
  "🐘",
  "🦏",
  "🦛",
  "🐭",
  "🐁",
  "🐀",
  "🐹",
  "🐰",
  "🐇",
  "🐿️",
  "🦔",
  "🦇",
  "🐻",
  "🐻‍❄️",
  "🐨",
  "🐼",
  "🦥",
  "🦦",
  "🦨",
  "🦘",
  "🦡",
  "🐾",
  "🦃",
  "🐔",
  "🐓",
  "🐣",
  "🐤",
  "🐥",
  "🐦",
  "🐧",
  "🕊️",
  "🦅",
  "🦆",
  "🦢",
  "🦉",
  "🦩",
  "🦚",
  "🦜",
  "🐸",
  "🐊",
  "🐢",
  "🦎",
  "🐍",
  "🐲",
  "🐉",
  "🦕",
  "🦖",
  "🐬",
  "🐟",
  "🐠",
  "🐡",
  "🦈",
  "🐙",
  "🐚",
  "🐌",
  "🦋",
  "🐛",
  "🐜",
  "🐝",
  "🐞",
  "🦗",
  "🕷️",
  "🦂",
  "🦟",
  "🦠",
  "💐",
  "🌸",
  "💮",
  "🏵️",
  "🌹",
  "🥀",
  "🌺",
  "🌻",
  "🌼",
  "🌷",
  "🌱",
  "🌲",
  "🌳",
  "🌴",
  "🌵",
  "🌾",
  "🌿",
  "☘️",
  "🍀",
  "🍁",
  "🍂",
  "🍃",
  "🍄",
]

export const DEGENS: Readonly<
  Record<string, { emoji: string } | { image: string }>
> = {
  "0xbcf96ceba85fb928b544872bec7e62d3490a439a16b7879578708bb711791f0e": {
    image: buffdoge_989553819539103764,
  },
  "0x0c691601793de060491dab143dfae19f5f6413d4ce4c363637e5ceacb2836a4e": {
    emoji: "🍺",
  },
  "0xdae3f7258eaae0ad7c9651c6bde22d99ca72652efa0b8d556b80d846d1ad7f58": {
    image: thuglife_989554541357834261,
  },
  "0x8aee4e164d5d70ac67308f303c7e063e9156903e42c1087bbc530447487fa47f": {
    image: heimdall_1005035405864869939,
  },
  "0x56daf75bd0f09c11d798263bc79baeb77c4b4af1dbd372bbe532b1f8702b2a7e": {
    image: kraken_1068218238074376193,
  },
  "0x5ae602686c9573bff2ef0483bda7a9589bc9eb7a2e14f91296367c5785394b27": {
    image: Parakeet_1074721851550466219,
  },
  "0x7ef19fdf6831748fb0c573516ec178d19b2326145f05d628d5716a9ed09b753a": {
    image: Charizard_1074723144209809519,
  },
  "0x00c30560019b1565ab9647c5b3134e325f46ce2c07438ba5b6ba80ee3685bd77": {
    image: bulbasaur_1064486523715719208,
  },
  "0x9e289d693888d1bf3bcfa508f827240c56ba2e28bf0f7e429d0fb5cfd867ff62": {
    image: sir_1069817913088946276,
  },
  "0x34cd97eea8d7958109c6db5e35eb407390555d9d07313768c374358cda816412": {
    emoji: "🌴",
  },
  "0x947c43d52db657492fed9368dc326e667d9c7bbf8df33c50974df47d2941ec42": {
    emoji: "🍄",
  },
  "0x6d6f646c70792f74727372790000000000000000000000000000000000000000": {
    emoji: "🏦",
  },
  "0x762f127097085ae29698892fd84a976ba88d56bf09637799558f8a53f71c9c23": {
    image: Dragonite_1074723182944198666,
  },
  "0xeca9d3ae4a822bba04af6186b0727b60585a284babb69e0606315b94b67faa3e": {
    image: Venusaur_1074723145518432268,
  },
  "0x6ae93e7162785a77d3a2c0413a9ee04af1b948ba5df9ac191552b72e1dd49b71": {
    emoji: "🦍",
  },
  "0x506172656e740000000000000000000000000000000000000000000000000000": {
    image: polkadot_1064520790978080818,
  },
  "0x853ad5c0b391c6150b09b9be883fd30e75d03957cbba2052c9efaa4a08660e17": {
    image: polkadot_1064520790978080818,
  },
  "0x471f92361b617ad6346d8993c5eb601b15704cd07c816efda5f5c32cbb095cf9": {
    image: polkadot_1064520790978080818,
  },
  "0xc5b7975df05c06a272ddc9d80cefafbe02d27c4303c04a8fc07df98000b48ab8": {
    image: polkadot_1064520790978080818,
  },
  "0x7369626cd4070000000000000000000000000000000000000000000000000000": {
    image: moonbeam_1390048945023094966,
  },
  "0x65feec15496516bcfde6b6b5df305163ed67e2be2703ccb69948a8d7a0b82e1f": {
    image: polkadot_1064520790978080818,
  },
  "0x45544800000000000000000000000000000000000000090a0000000000000000": {
    image: HOLLAR_1419786409664970834,
  },
  "0x2c9cb9a8e415f13e70494c9f54e9d9d7740b6104eba196440b1bc9eacc774d09": {
    image: HDX_1419786558357377185,
  },
}
