export const XC_SWAP_QUOTE_DEBOUNCE_MS = 300

export const XC_SWAP_CHAIN_ITEM_HEIGHT = 40
export const XC_SWAP_MAX_VISIBLE_CHAIN_ITEMS = 10

export const XC_SWAP_ASSET_ITEM_HEIGHT = 50
export const XC_SWAP_MAX_VISIBLE_ASSET_ITEMS = 8
